name: fie_stream_clipper
description: "Tool to separate FIE streams into bouts"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  file_picker: ^8.1.7
  ffi: any
  path_provider: ^2.0.12
  path: any
  url_launcher: any
  desktop_drop: 0.5.0
  window_size:
    git:
      url: https://github.com/google/flutter-desktop-embedding.git
      path: plugins/window_size
      ref: fd519be1e8398c6b6c2062c2447bac960a71bc02

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - ./assets/svm_model.xml
    - ./assets/tessdata/
    - ./assets/overlays/
