name: fie_stream_clipper
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  file_picker: ^8.1.7
  ffi: any
  path_provider: ^2.0.12
  path: any
  url_launcher: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - ./assets/archive.dll
    - ./assets/bz2.dll
    - ./assets/gif.dll
    - ./assets/jpeg62.dll
    - ./assets/leptonica-1.85.0.dll
    - ./assets/libcrypto-3-x64.dll
    - ./assets/libcurl.dll
    - ./assets/liblzma.dll
    - ./assets/libpng16.dll
    - ./assets/libsharpyuv.dll
    - ./assets/libwebp.dll
    - ./assets/libwebpmux.dll
    - ./assets/lz4.dll
    - ./assets/openjp2.dll
    - ./assets/tesseract55.dll
    - ./assets/tiff.dll
    - ./assets/video_review.dll
    - ./assets/video_review.exp
    - ./assets/video_review.lib
    - ./assets/zlib1.dll
    - ./assets/zstd.dll
    - ./assets/svm_model.xml
